### ISSUE TITLE
Jo Der Compiler geht nicht

### ISSUE THREAD

**Issue by zweehn** [EMBaudert/CCompiler#1]
Ich habe compile im terminal eingegeben und es sagt dass die ausführbare Datei nicht gefunden Wurde?????

**Comment by pa-os** [comment]
It's not a bug. It's a feature!

**Comment by time2323** [comment]
geht net

**Comment by time2323** [comment]
Wir arbeiten daran...

**Comment by time2323** [comment]
Tut mir sehr leid, wir konnten das Problem nicht lösen.
